name: pey
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animated_list_plus: ^0.5.2
  auto_animated: ^3.2.0
  bloc: ^8.1.2
  cached_memory_image: ^1.3.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.10.0
  cross_fade: ^0.3.1
  dart_date: ^1.3.2
  dartz: ^0.10.1
  dash_chat_2: ^0.0.18
  date_format: ^2.0.7
  dio: ^5.3.2
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  expandable: ^5.0.1
  extended_tabs: ^4.1.0
  fade_indexed_stack: ^0.2.2
  firebase_analytics: ^10.5.0
  firebase_core: ^2.18.0
  firebase_dynamic_links: ^5.3.6
  firebase_pagination: ^3.0.0
  firebase_storage: ^11.4.0

  step_progress_indicator: ^1.0.2

  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_custom_clippers: ^2.1.0
  flutter_gif: ^0.0.4
  flutter_local_notifications: ^15.1.1

  flex_color_scheme: ^7.3.1

  flutter_native_splash: ^2.3.2
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.4
  glassmorphism: ^3.0.0
  google_fonts: ^5.1.0
  gradient_borders: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http_parser: ^4.0.2
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  like_button: ^2.0.5
  local_auth: ^2.1.7
  lottie: ^2.6.0
  mime: ^1.0.4
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  photo_manager: ^2.7.1
  pin_keyboard: ^1.1.2
  pinput: ^3.0.1
  share_plus: ^7.2.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  stacked: ^3.4.1+1
  story_view: ^0.15.0
  timezone: ^0.9.2
  uuid: ^3.0.4
  validatorless: ^1.2.3
  video_player: ^2.7.2
  video_thumbnail: ^0.5.3
  flutter_logs: ^2.1.11
  video_trimmer: ^3.0.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svgs/
    - assets/tunes/
    - assets/fonts/
    - assets/animated/
    - assets/icons/

  fonts:
    - family: PeyIcons
      fonts:
        - asset: assets/fonts/PeyIcons.ttf
