// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAziTatUHvtWoNAvUaaOe3C0Egvgf20wBM',
    appId: '1:397738794795:web:fa060594e9738140526f6e',
    messagingSenderId: '397738794795',
    projectId: 'pey-rv',
    authDomain: 'pey-rv.firebaseapp.com',
    storageBucket: 'pey-rv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3yfPYNA3jdk5TtKOtclCc4fErZykDpHY',
    appId: '1:397738794795:android:d04d503a2cd757c7526f6e',
    messagingSenderId: '397738794795',
    projectId: 'pey-rv',
    storageBucket: 'pey-rv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvwKJHWKXaF9nO1_I5d17X0SUEHA9xymc',
    appId: '1:397738794795:ios:87e8ea8164078866526f6e',
    messagingSenderId: '397738794795',
    projectId: 'pey-rv',
    storageBucket: 'pey-rv.appspot.com',
    iosBundleId: 'com.example.pey',
  );
}
